version: '3.8'

services:
  comfyui-worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: nedisonn/nv-comfyui-worker:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - SERVE_API_LOCALLY=true
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "8000:8000"
      - "8188:8188"
    volumes:
      - ./data/comfyui/output:/runpod-volume/output
      - ./data/runpod-volume:/runpod-volume